### ISSUE TITLE
Discriminator output

### ISSUE THREAD

**Issue by hzx829** [ChengBinJin/WGAN-TensorFlow#1]
I guess in WGAN, we shouldn't add sigmoid at the end of discriminator?
Do you have some special reason to do so?
Thank you

**Comment by ChengBinJin** [comment]
> I guess in WGAN, we shouldn't add sigmoid at the end of discriminator?
> Do you have some special reason to do so?
> Thank you

Yes, you are right. We don't need to add sigmoid at the end of the discriminator.
I returned two variables, the first one is sigmoid of the output, and the second is the output.
When calculating the discriminator loss, I used the second output which is not used sigmoid.
The output with sigmoid is just using for debugging for the loss.
